apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::503947560776:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1BIWJXLAMBP9B
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::503947560776:role/UdacityFlaskDeployCBKubectlRole
   username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-14T21:38:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2022-08-14T21:38:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1605"
  uid: caa391ef-94c6-416a-a9b8-190c36b952fd
